import * as cop from '../../src'; 

// Create main data collection
const collection = new cop.elements.ElementCollection();

// Add header for table of content
const toc = new cop.elements.TableOfContents(
    "toc_demo",
    "Table of Contents- Generated by AOP",
    2,
    "hyphen"
);
collection.add(toc);

//customer data
const customers = [
    {
        cust_f_name: "John",
        cust_l_name: "Dulles",
        city: "Sterling",
        addr_1: "45020 Aviation Drive",
        state: "VA",
        email: "john.dulles@email.com",
        phone_number_1: "703-555-2143",
        phone_number_2: "703-555-8967",
        url: "http://www.johndulles.com"
    },
    {   
        cust_f_name: "Fiorello",
        cust_l_name: "LaGuardia",
        city: "Flushing",
        addr_1: "Hangar Center",
        addr_2: "Third Floor",
        state: "NY",
        phone_number_1: "212-555-3923"
    },
    {
        cust_f_name: "Albert",
        cust_l_name: "Lambert",
        city: "St. Louis",
        addr_1: "10701 Lambert International Blvd.",
        state: "MO",
        phone_number_1: "314-555-4022"
    }
];

// Create a customer collections
const customerCollections = customers.map(customer => 
    cop.elements.ElementCollection.fromMapping(customer)
);

// Add customers to main collection
const customersLoop = new cop.elements.ForEach("cust_list", customerCollections);
collection.add(customersLoop);

// Add Html
const htmlContent = `
<h1>Heading 1 from html</h1>
<h2>Heading 2 from html</h2>
<h3>Heading 3 from html</h3>
aop also handles the headings from html`;

collection.add(new cop.elements.Html(
    "sample_html",
    htmlContent,
    undefined, //customTableStyle
    undefined, //unorderedListStyle
    undefined,  //orderedListStyle
    true, //useTagStyle
    undefined, //ignoreCellMargin
    undefined  //ignoreEmptyP
));

// Add server
  // If you are using onpremise-version do not need to specify YOUR_API_KEY else replace it with your api key.
  const server = new cop.config.Server(
      "http://localhost:8010/",
      new cop.config.ServerConfig("YOUR_API_KEY"),
  );
  

// Create print job
const printjob = new cop.PrintJob(
    collection,
    server,
    cop.Resource.fromLocalFile("./data/toc_temp.docx")
);

// Asynchronously execute print job and save response to file
(async () => {
    try{
        const response = await printjob.execute();
        await response.toFile("./output/output.docx");
    }catch(err){
        console.log(err);
    }
})()